#!/usr/bin/env python3
"""Regenerate .vscode/c_cpp_properties.json from the live arduino-cli toolchain.

Run via `make vscode` (or as part of `make upgrade`) so a core upgrade never
leaves IntelliSense pointing at stale version paths. Paths come from
`arduino-cli compile --show-properties`, i.e. the same resolution the real
build uses.
"""
import json
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FQBN = "esp32:esp32:esp32s3"
SKETCH = REPO / "firmware" / "tap_light"
OUT = REPO / ".vscode" / "c_cpp_properties.json"


def run(*args):
    return subprocess.run(args, check=True, capture_output=True, text=True).stdout


props = {}
for line in run("arduino-cli", "compile", "--show-properties",
                "--fqbn", FQBN, str(SKETCH)).splitlines():
    key, sep, value = line.partition("=")
    if sep:
        props[key] = value

core = props["runtime.platform.path"]
sdk = props["compiler.sdk.path"]
compiler = props["compiler.path"] + props["compiler.prefix"] + "g++"
core_dir = f"{core}/cores/{props['build.core']}"
user_libs = run("arduino-cli", "config", "get", "directories.user").strip() + "/libraries"

# The SDK ships the exact include roots the compiler is invoked with
# (flags/includes, entries relative to <sdk>/include/). Expanding them here —
# rather than relying on a recursive glob — makes IntelliSense resolve nested
# roots like soc/esp32s3/include, which guards e.g. WiFi.h's SOC_WIFI_SUPPORTED.
sdk_includes = []
tokens = (Path(sdk) / "flags" / "includes").read_text().split()
for prev, tok in zip(["", *tokens], tokens):
    if prev == "-iwithprefixbefore":
        sdk_includes.append(f"{sdk}/include/{tok}")

home = str(Path.home())


def tidy(path):
    return path.replace(home, "${env:HOME}")


config = {
    "version": 4,
    "configurations": [{
        "name": "ESP32-S3 (arduino-cli)",
        "compilerPath": tidy(compiler),
        "cStandard": "gnu17",
        "cppStandard": "gnu++17",
        "includePath": [
            "${workspaceFolder}/firmware/**",
            tidy(core_dir),
            tidy(f"{core}/variants/{props['build.variant']}"),
            tidy(f"{core}/libraries/**"),
            *[tidy(p) for p in sdk_includes],
            tidy(f"{sdk}/{props['build.memory_type']}/include"),
            tidy(f"{user_libs}/**"),
        ],
        "forcedInclude": [tidy(f"{core_dir}/Arduino.h")],
        "defines": [
            "ESP32",
            "ESP_PLATFORM",
            f"ARDUINO={props.get('runtime.ide.version', '10607')}",
            "ARDUINO_ARCH_ESP32",
            "ARDUINO_ESP32S3_DEV",
            "CONFIG_IDF_TARGET_ESP32S3=1",
            f"F_CPU={props.get('build.f_cpu', '240000000L')}",
            "ARDUINO_USB_MODE=1",
            f"ARDUINO_USB_CDC_ON_BOOT={props.get('build.cdc_on_boot', '0')}",
        ],
    }],
}

OUT.parent.mkdir(exist_ok=True)
OUT.write_text(
    "// Generated by scripts/gen_intellisense.py — run `make vscode` to refresh\n"
    "// (e.g. after a core upgrade). Manual edits will be overwritten.\n"
    + json.dumps(config, indent=2) + "\n")
print(f"Wrote {OUT.relative_to(REPO)}  (core {Path(core).name}, sdk {Path(sdk).name})")
